name: Process FOTA Package

on:
  workflow_dispatch:
    inputs:
      url:
        description: URL of the FOTA Package
      branch:
        description: Branch name of the git repository
      mask:
        description: Mask sensitive parts of the URL
        type: boolean
        default: false

jobs:
  process:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Mask sensitive parts of the URL
        if: ${{ inputs.mask }}
        run: |
          SENSITIVE_PART_1=$(jq -r '.inputs.url' $GITHUB_EVENT_PATH | grep -Po '/ZTE/.+/\K([0-9]+)')
          echo ::add-mask::$SENSITIVE_PART_1
          SENSITIVE_PART_2=$(jq -r '.inputs.url' $GITHUB_EVENT_PATH | grep -Po '/ZTE/.+/([0-9]+)/\K.+?(?=GEN_)')
          echo ::add-mask::$SENSITIVE_PART_2

      - name: Clone Python scripts for CI
        uses: actions/checkout@v6
        with:
          ref: _ci

      - name: Clone existing data
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.branch }}
          path: repo

      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Process FOTA package
        run: python -u process.py '${{ github.event.inputs.url }}' repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVICE_MODELS: ${{ vars.DEVICE_MODELS }}
